In [1]:
import numpy as np

# Creating a numpy array from 1 to 10
array = np.arange(1, 11)

# Reshape the array to a 2x5 matrix
reshaped_array = array.reshape(2, 5)

print(reshaped_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
import numpy as np

# Creating a numpy array from 1 to 20
array = np.arange(1, 21)

# Extract elements between the 5th and 15th index
extracted_elements = array[4:15] 

print(extracted_elements)


[ 5  6  7  8  9 10 11 12 13 14 15]


In [5]:
import pandas as pd

# Creating a pandas series
series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Add a new item to the series
series['pears'] = 4

print(series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [7]:
import pandas as pd
import numpy as np

# Generating random data for the dataframe
data = {
    'name': [f'Person {i}' for i in range(1, 11)],
    'age': np.random.randint(20, 50, size=10),
    'gender': np.random.choice(['Male', 'Female'], size=10)
}

# Create a dataframe
df = pd.DataFrame(data)

print(df)


        name  age  gender
0   Person 1   26  Female
1   Person 2   38  Female
2   Person 3   41    Male
3   Person 4   42  Female
4   Person 5   45  Female
5   Person 6   27  Female
6   Person 7   40    Male
7   Person 8   43  Female
8   Person 9   32    Male
9  Person 10   34    Male


In [9]:
import pandas as pd
import numpy as np

# Generating random data for the dataframe
data = {
    'name': [f'Person {i}' for i in range(1, 11)],
    'age': np.random.randint(20, 50, size=10),
    'gender': np.random.choice(['Male', 'Female'], size=10)
}

# Create a dataframe
df = pd.DataFrame(data)

occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['Occupation'] = occupations[:10] 

print(df)

        name  age  gender  Occupation
0   Person 1   20    Male  Programmer
1   Person 2   33  Female     Manager
2   Person 3   38  Female     Analyst
3   Person 4   41    Male  Programmer
4   Person 5   44    Male     Manager
5   Person 6   29  Female     Analyst
6   Person 7   48  Female  Programmer
7   Person 8   22  Female     Manager
8   Person 9   31    Male     Analyst
9  Person 10   23    Male  Programmer


In [11]:
import pandas as pd
import numpy as np

# Generating random data for the dataframe
data = {
    'name': [f'Person {i}' for i in range(1, 11)],
    'age': np.random.randint(20, 50, size=10),
    'gender': np.random.choice(['Male', 'Female'], size=10)
}

# Create a dataframe
df = pd.DataFrame(data)

occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['Occupation'] = occupations[:10] 

# Select rows where age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]

print(filtered_df)

        name  age  gender  Occupation
1   Person 2   30  Female     Manager
2   Person 3   33    Male     Analyst
3   Person 4   40  Female  Programmer
4   Person 5   43  Female     Manager
6   Person 7   49    Male  Programmer
7   Person 8   44  Female     Manager
9  Person 10   48    Male  Programmer


In [13]:
import pandas as pd
import numpy as np

# Generating random data for the dataframe
data = {
    'name': [f'Person {i}' for i in range(1, 11)],
    'age': np.random.randint(20, 50, size=10),
    'gender': np.random.choice(['Male', 'Female'], size=10)
}

# Create a dataframe
df = pd.DataFrame(data)

occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['Occupation'] = occupations[:10] 

# Save the dataframe to a csv file
df.to_csv('data.csv', index=False)

# Read the csv file
read_df = pd.read_csv('data.csv')

print(read_df)


        name  age  gender  Occupation
0   Person 1   39  Female  Programmer
1   Person 2   25    Male     Manager
2   Person 3   47  Female     Analyst
3   Person 4   23  Female  Programmer
4   Person 5   49    Male     Manager
5   Person 6   47  Female     Analyst
6   Person 7   49  Female  Programmer
7   Person 8   36    Male     Manager
8   Person 9   32  Female     Analyst
9  Person 10   33    Male  Programmer
